-- INSERT INTO categories (name) VALUES
--                                   ('의류'),
--                                   ('가방'),
--                                   ('열쇠'),
--                                   ('문서'),
--                                   ('기타');